/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x66, 0x8F, 0x22, 0x2F, 0x54, 0xB4, 0xD9, 0x99}

#define DYNAMIC_KEYMAP_LAYER_COUNT 2

#ifdef POINTING_DEVICE_ENABLE
    #define ANALOG_JOYSTICK_X_AXIS_PIN D4
    #define ANALOG_JOYSTICK_Y_AXIS_PIN C6
    #define ANALOG_JOYSTICK_AXIS_MIN 10
    #define ANALOG_JOYSTICK_AXIS_MAX 1023
    #define ANALOG_JOYSTICK_SPEED_REGULATOR 40
    #define ANALOG_JOYSTICK_READ_INTERVAL 10
    #define ANALOG_JOYSTICK_SPEED_MAX 2
#endif