/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

/* Split hand configration */
#define SPLIT_HAND_MATRIX_GRID D4, F4
#define SPLIT_HAND_MATRIX_GRID_LOW_IS_RIGHT

#define VIAL_KEYBOARD_UID {0xBB, 0x25, 0x78, 0x78, 0xFD, 0x38, 0xB3, 0x6D}

#define VIAL_ENCODER_DEFAULT { KC_VOLU, KC_VOLD, KC_PGUP, KC_PGDOWN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS }

#define DYNAMIC_KEYMAP_LAYER_COUNT 3
