#pragma once

#define VIAL_KEYBOARD_UID {0x91, 0x2B, 0x26, 0xFF, 0xB0, 0xE5, 0xDC, 0x83}

#define DYNAMIC_KEYMAP_LAYER_COUNT 2
#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE
#define DYNAMIC_KEYMAP_MACRO_COUNT 8