#pragma once

#define VIAL_KEYBOARD_UID {0x3D, 0xDC, 0x35, 0xC3, 0x6D, 0x4A, 0x9C, 0x49}

#define VIAL_ENCODER_DEFAULT { \
    KC_VOLU, KC_VOLD, \
    KC_PGUP, KC_PGDN, \
    KC_TRNS, KC_TRNS, \
    KC_TRNS, KC_TRNS, \
    KC_TRNS, KC_TRNS, \
    KC_TRNS, KC_TRNS, \
    KC_TRNS, KC_TRNS, \
    KC_TRNS, KC_TRNS \
}

#define DYNAMIC_KEYMAP_LAYER_COUNT 10
